---
title: "The Great Debate"
output: 
  flexdashboard::flex_dashboard:
  orientation: columns
vertical_layout: fill
runtime: shiny
---
  
```{r setup, include=FALSE}    
library(flexdashboard)
library(tidyverse)
library(DT)
library(shiny)
table_transition <- read_csv(
  file = "data-raw/LA_TRANSITION_ECOLOGIQUE.csv"
  ) %>%
  set_names(
    nm = names(.) %>%
    sub(
      pattern = "^(Q[[:digit:]]+).*", 
      replacement = "\\1", 
      x = .)
    )

table_transition %>%
  select(reference, starts_with("Q")) %>%
  gather(key = question, value = contribution, -reference) %>%
  filter(is.na(contribution) == FALSE) 

table_grandeannotation <- read_csv(
  file = "data-raw/actions.csv"
  ) 

table_annotations <- table_grandeannotation %>% 
  select(Contribution, Question, Categorie) %>%
  mutate(Question = paste0("Q", Question)) %>%
  distinct() %>%
  left_join(
    y = table_transition %>%
      select(reference, starts_with("Q")) %>%
      gather(key = question, value = contribution, -reference) %>%
      filter(is.na(contribution) == FALSE),  
    by = c(
      "Question" = "question", 
      "Contribution" = "reference"
      )    
    )
```

Column {data-width=200 .sidebar}
-----------------------------------------------------------------------
  
```{r}
selectInput(
  "x_input", 
  label = "Sélectionnez une question",
  choices = unique(as.character(table_annotations$Question)), 
  selected = "Q160"
  )

roster_input <- reactive({
    table_annotations %>% 
      filter(
        Question == input$x_input
        ) %>%
      select(Categorie, Contribution, contribution) %>%
      mutate(
        Categorie = as.factor(Categorie), 
        Contribution = as.factor(Contribution)
        )   
    }
  )
```

Column {data-width=350}
-----------------------------------------------------------------------
  
### Chart B
  
```{r}
renderDT({
  DT::datatable(
    roster_input(),
    rownames = FALSE, 
    filter = list(position = 'top', clear = FALSE), 
    options = list(
      searchHighlight = TRUE,
      search = list(regex = TRUE, caseInsensitive = FALSE, search = 'Pollution[s]?'),
      pageLength = 10, 
      autoWidth = TRUE
      )
    )
  }
  )
```